CREATE TABLE IF NOT EXISTS employee
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(30) NOT NULL,
  lastname VARCHAR(30) NOT NULL,
  role INT NOT NULL,
  password VARCHAR(64) NOT NULL
);
